apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
  name: example-app
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example-app
  sessionAffinity: None
  type: ClusterIP
