apiVersion: v1
kind: Service
metadata:
  name: kubeshark-front-nodeport
  namespace: default
  labels:
    app.kubernetes.io/instance: kubeshark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeshark
    app.kubernetes.io/version: 52.3.68
    helm.sh/chart: kubeshark-52.3.68
  annotations:
    meta.helm.sh/release-name: kubeshark
    meta.helm.sh/release-namespace: default
spec:
  type: NodePort
  selector:
    app.kubeshark.co/app: front
  ports:
  - port: 8899
    targetPort: 8899
    protocol: TCP
    nodePort: 30899 # 원하는 NodePort 번호로 변경 가능
