apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ygtoken/ghost-blog # DockerHub에 업로드한 이미지 이름
        env:
        - name: NODE_ENV
          value: development
        - name: url
          value: http://localhost:3001 # 원하는 URL 설정
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-data # 볼륨 이름
          mountPath: /mnt/ghost # 컨테이너 내 마운트 경로
      volumes:
      - name: ghost-data
        hostPath:
          path: /mnt/ghost # 호스트 머신의 실제 경로
          type: DirectoryOrCreate # 호스트 경로가 없으면 생성하도록 설정
