apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ygtoken/ghost-blog:latest
        env:
        - name: NODE_ENV
          value: development
        - name: url
          value: http://localhost:3001
        ports:
        - containerPort: 2368
