apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env:
        - name: NODE_ENV
          value: development
        - name: url
          value: http://192.168.219.42:30268
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-data
          mountPath: /mnt/ghost
      volumes:
      - name: ghost-data
        hostPath:
          path: /mnt/ghost
          type: DirectoryOrCreate
