apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  type: NodePort
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 80 # Service에 노출할 포트
    targetPort: 2368 # Deployment의 컨테이너 포트
    nodePort: 30001 # NodePort로 사용할 포트 번호 (사용 가능한 범위에서 선택)
