apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamafile-server
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llamafile-server
  template:
    metadata:
      labels:
        app: llamafile-server
    spec:
      containers:
      - name: llamafile-server
        image: ygtoken/llm-service # Docker Hub에 업로드한 이미지 이름
        ports:
        - containerPort: 8080 # 컨테이너 내부의 포트
