apiVersion: v1
kind: Service
metadata:
  name: llamafile-server
  namespace: llm
spec:
  selector:
    app: llamafile-server
  ports:
  - protocol: TCP
    port: 8080 # 서비스의 포트
    targetPort: 8080 # 파드의 포트
  type: NodePort # 서비스 유형을 NodePort로 지정
